import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { UserActions } from "@/components/admin/user-actions";
import { loadAdminUserDetail } from "@/lib/admin/data";

export const metadata: Metadata = { title: "Utilisateur — cockpit", robots: { index: false, follow: false } };

export default async function AdminUserDetail({ params }: PageProps<"/admin/users/[id]">) {
  const {id}=await params; const data=await loadAdminUserDetail(id); if(!data)notFound();
  return <main id="contenu" className="mx-auto flex w-full max-w-5xl flex-1 flex-col gap-10 px-4 py-10 sm:px-6"><div><Link href="/admin/users" className="link text-small">Tous les utilisateurs</Link><h1 className="text-h1 mt-3">{data.profile.email??"Compte sans email"}</h1><p className="text-small text-attenue">Créé le {new Date(data.profile.created_at).toLocaleString("fr-FR")} · dernière activité {new Date(data.lastActivity).toLocaleString("fr-FR")}</p></div>
    <section className="grid gap-px border border-filet bg-filet sm:grid-cols-3">{[["Accès",data.paid?"Pro — abonnement actif":data.activeGrant?"Pro — accès offert":data.credits?.balance?"Pack":"Gratuit"],["Crédits",String(data.credits?.balance??0)],["Analyses",String(data.deals.reduce((sum,d)=>sum+d.analyses.length,0))]].map(([l,v])=><div key={l} className="bg-creme p-5"><p className="text-small text-attenue">{l}</p><p className="mt-1 font-bold text-encre">{v}</p></div>)}</section>
    <UserActions userId={id} hasGrant={Boolean(data.activeGrant)} />
    <section><h2 className="text-h2 mb-4">Historique des crédits</h2>{data.ledger.length===0?<p className="text-attenue">Aucun ajustement admin.</p>:<ul className="divide-y">{data.ledger.map(row=><li key={row.id} className="grid gap-1 py-3 sm:grid-cols-[7rem_1fr_10rem]"><strong>{row.delta>0?"+":""}{row.delta}</strong><span>{row.reason}</span><span className="text-small text-attenue">{row.balance_before} → {row.balance_after}</span></li>)}</ul>}</section>
    <section><h2 className="text-h2 mb-4">Analyses et négociations</h2>{data.deals.length===0?<p className="text-attenue">Aucune analyse.</p>:<ul className="divide-y">{data.deals.map(deal=><li key={deal.id} className="flex justify-between gap-4 py-3"><span>{new Date(deal.created_at).toLocaleString("fr-FR")} · {deal.status}</span><span>{deal.analyses.length} résultat(s)</span></li>)}</ul>}</section>
    <section><h2 className="text-h2 mb-4">Tours de négociation</h2>{data.turns.length===0?<p className="text-attenue">Aucun tour de négociation.</p>:<ul className="divide-y">{data.turns.map(turn=><li key={turn.id} className="flex justify-between gap-4 py-3"><span>{turn.kind==="conclusion"?"Conclusion":`Tour ${turn.turn_number??"—"}`} · analyse {turn.analysis_id}</span><span className="text-small text-attenue">{new Date(turn.created_at).toLocaleString("fr-FR")}</span></li>)}</ul>}</section>
    <section><h2 className="text-h2 mb-4">Acquisition et événements récents</h2>{data.events.length===0?<p className="text-attenue">Aucune attribution disponible.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-small"><thead><tr className="border-b"><th className="py-2">Date</th><th>Événement</th><th>Source</th><th>Medium</th><th>Campagne</th><th>Contenu</th></tr></thead><tbody>{data.events.map(event=><tr key={event.id} className="border-b"><td className="py-2">{new Date(event.occurred_at).toLocaleString("fr-FR")}</td><td>{event.event_name}</td><td>{event.utm_source??"—"}</td><td>{event.utm_medium??"—"}</td><td>{event.utm_campaign??"—"}</td><td>{event.utm_content??"—"}</td></tr>)}</tbody></table></div>}</section>
    <section className="grid gap-8 lg:grid-cols-2"><div><h2 className="text-h2 mb-4">Feedback</h2>{data.feedback.length===0?<p className="text-attenue">Aucun feedback.</p>:<ul>{data.feedback.map(f=><li key={`${f.analysis_id}-${f.updated_at}`} className="border-b py-2">{f.rating} · {new Date(f.updated_at).toLocaleString("fr-FR")}</li>)}</ul>}</div><div><h2 className="text-h2 mb-4">Audit admin</h2>{data.audit.length===0?<p className="text-attenue">Aucune action.</p>:<ul>{data.audit.map(a=><li key={a.id} className="border-b py-2"><strong>{a.action}</strong> · {a.reason??"sans motif"}<br/><span className="text-xs text-attenue">{new Date(a.occurred_at).toLocaleString("fr-FR")}</span></li>)}</ul>}</div></section>
  </main>;
}
